logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapp-main/webapp.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    mapping-severity:
      type: modify_fields
      fields: 
        mapping-severity:
          copy_from: jsonPayload.level
          map_level_values:
            "info": "INFO"
            "error": "ERROR"
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, mapping-severity]