name: Node.js CI

on:
  push:
    branches: [main]

env:
  HOST: ${{  secrets.HOST  }}
  DB_USER: ${{  secrets.DB_USER  }}
  PASSWORD: ${{  secrets.PASSWORD  }}
  DATABASE: ${{  secrets.DATABASE  }}
  ENV: ${{  secrets.ENV  }}

jobs:
  packer-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to webapp
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Create .env
        run: touch .env

      - name: Generate ZIP file
        run: zip -r webapp-a2-main.zip .
 
      - name: Install dependencies
        run: npm ci

      - name: Start mysql server
        run: sudo systemctl start mysql

      - name: GCLOUD SA validation
        uses: "google-github-actions/auth@v2"
        with:
            credentials_json: "${{ secrets.GCP_SA_Key}}"

      - name: Test
        run: npm test

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Install Packer   
        run: packer init centos-nodejs-using-packer.pkr.hcl

      - name: Packer Build
        run: packer build centos-nodejs-using-packer.pkr.hcl
