name: Node.js CI

on:
  pull_request:
    branches: [main]

env:
  HOST: ${{  secrets.HOST  }}
  USER: ${{  secrets.USER  }}
  PASSWORD: ${{  secrets.PASSWORD  }}
  DATABASE: ${{  secrets.DATABASE  }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to webapp
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # - name: Install MySQL Client
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y mysql-client

      - name: Install dependencies
        run: npm ci

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            sleep 1
          done

      - name: Prepare database
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DATABASE }};"
          

      - name: start mysql server
        run: sudo systemctl start mysql

      - name: Test
        run: npm test
