name: Node.js CI

on:
  pull_request:
    branches: [main]

env:
  HOST: ${{  secrets.HOST  }}
  DB_USER: ${{  secrets.DB_USER  }}
  PASSWORD: ${{  secrets.PASSWORD  }}
  DATABASE: ${{  secrets.DATABASE  }}
  ENV: ${{  secrets.ENV  }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to webapp
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Generate ZIP file
        run: zip -r webapp-a2-main.zip .

        
      - name: Install dependencies
        run: npm ci

      - name: Start mysql server
        run: sudo systemctl start mysql

      - name: Test
        run: npm test
