name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout to webapp 
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: start mysql server
      run: sudo systemctl start mysql.service

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm test
